[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/.next"

  [build]
  command = "npm install && npm run build"
  publish = "build"


[build]
  command = "npm install && npm run build && npm run export"
  publish = "out"


[functions]
  directory = "functions"

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200

