[build]
  base = "raza"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"


[function]
  directory = "function"

[[redirects]]
  from = "/send-email"
  to = "/.netlify/function/send-email"
  status = 200
  methods = ["POST"]
