[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  function = "function"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
  from = "/send-email"
  to = "/.netlify/function/send-email"
  status = 200
  methods = ["POST"]
