[build]
command = "npm install && npm run build"
publish = "build"


[functions]
  directory = "functions"

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200

