[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/.next"

[functions]
  directory = "functions"

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
